SET NOCOUNT ON;
DECLARE @Page TABLE(Id int);
INSERT @Page SELECT ProductId FROM dbo.Products WHERE IsActive=1 AND Name LIKE N'%Keyboard%' AND Price BETWEEN 400000 AND 3000000 ORDER BY Price DESC,ProductId OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;
IF (SELECT COUNT(*) FROM @Page)<>3 OR EXISTS(SELECT Id FROM @Page EXCEPT SELECT Id FROM (VALUES(8),(2),(1)) v(Id)) THROW 52005,'page fixture',1;
BEGIN TRAN;
INSERT dbo.Products(Name,Price,IsActive,CreatedAt) VALUES(N'Keyboard tie',1200000,1,'2026-01-01');
IF (SELECT TOP(1) ProductId FROM dbo.Products WHERE Price=1200000 ORDER BY Price DESC,ProductId)<>1 THROW 52005,'tie breaker',1;
ROLLBACK;
SELECT 'CONTRACT_OK';
