SET NOCOUNT ON;
IF (SELECT COUNT(*) FROM (SELECT Sku FROM dbo.CatalogA UNION SELECT Sku FROM dbo.CatalogB) x)<>5 OR (SELECT COUNT(*) FROM (SELECT Sku FROM dbo.CatalogA UNION ALL SELECT Sku FROM dbo.CatalogB) x)<>6 THROW 52010,'union multiplicity',1;
IF (SELECT Sku FROM dbo.CatalogA INTERSECT SELECT Sku FROM dbo.CatalogB)<>'COMMON-01' THROW 52010,'intersection',1;
IF (SELECT COUNT(*) FROM (SELECT Sku FROM dbo.CatalogA EXCEPT SELECT Sku FROM dbo.CatalogB) x)<>2 THROW 52010,'except',1;
IF (SELECT COUNT(*) FROM (SELECT CAST(NULL AS int) AS v UNION SELECT CAST(NULL AS int)) x)<>1 THROW 52010,'NULL dedup',1;
SELECT 'CONTRACT_OK';
