SET NOCOUNT ON;
SELECT OrderId,ROW_NUMBER() OVER(PARTITION BY CustomerId ORDER BY TotalAmount DESC,OrderId) rn,RANK() OVER(PARTITION BY CustomerId ORDER BY TotalAmount DESC) r,DENSE_RANK() OVER(PARTITION BY CustomerId ORDER BY TotalAmount DESC) dr,SUM(TotalAmount) OVER(PARTITION BY CustomerId ORDER BY OrderedAt,OrderId ROWS UNBOUNDED PRECEDING) running,LAG(TotalAmount) OVER(PARTITION BY CustomerId ORDER BY OrderedAt,OrderId) prev INTO #Window FROM dbo.Orders;
IF NOT EXISTS(SELECT 1 FROM #Window WHERE OrderId=101 AND rn=3 AND r=3 AND dr=2 AND running=1000000 AND prev IS NULL) OR NOT EXISTS(SELECT 1 FROM #Window WHERE OrderId=103 AND rn=2 AND r=1 AND dr=1 AND running=7000000 AND prev=3000000) THROW 52012,'ranking/frame',1;
IF (SELECT COUNT(*) FROM #Window WHERE rn<=2)<>4 THROW 52012,'top two',1;
SELECT 'CONTRACT_OK';
